export const CHACK_CONNECTION_REQUEST = 'CHACK_CONNECTION_REQUEST';
export const CHACK_CONNECTION_SUCCESS = 'CHACK_CONNECTION_SUCCESS';
export const CHACK_CONNECTION_FAIL = 'CHACK_CONNECTION_FAIL';
export const CHACK_CONNECTION_FOR_SERVER_REQUEST = 'CHACK_CONNECTION_FOR_SERVER_REQUEST';
export const CHACK_CONNECTION_FOR_SERVER_SUCCESS = 'CHACK_CONNECTION_FOR_SERVER_SUCCESS';
export const CHACK_CONNECTION_FOR_SERVER_FAIL = 'CHACK_CONNECTION_FOR_SERVER_FAIL';
